name: "Automerger"
on: 
  - pull_request
  - pull_request_review
  - status

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: pascalgn/automerge-action@v0.2.4
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        merge-method: squash
